version: "3"
services:
  mysql:
    image: mysql:5.7
    container_name: webdict
    restart: always
    volumes:
      - ./mysql-init/:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ROOT_PASSWORD=ustc123123
      # 指定初始化sql文件的数据库
      - MYSQL_DATABASE=webdict
      - TZ=Asia/Shanghai
    ports:
      - 3306:3306
  redis:
    image: redis
    container_name: webdict-redis
    restart: always
    ports:
      - 6379:6379