name: Build & Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build
        run: |
          go mod download
          go build -o ./output/webdict_server ./src/main/main.go
          cp ./run.sh ./output
          cp ./app.properties ./output

      - name: Deploy
        uses: SamKirkland/FTP-Deploy-Action@2.0.0
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          LOCAL_DIR: "./output/"
          REMOTE_DIR: ${{ secrets.REMOTE_DIR }}
          METHOD: sftp
          PORT: ${{ secrets.FTP_PORT }}

      - name: Run The Server
        uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
        with:
          host: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          key: ${{ secrets.PRIVATE_KEY}}
          pass: ${{ secrets.FTP_PASSWORD}}
          last_ssh: |
            nohup bash /www/wwwroot/webdict_server/run.sh > /www/wwwroot/webdict_server/nohup.log 2>&1 &
