name: Build & Test

on:
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build
        run: |
          go mod download
          go build -o ./output/webdict_server ./src/main/main.go
          cp ./run.sh ./output
          cp ./app.properties ./output

      - name: Test
        run: |
          ./output/webdict_server
