name: Test

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Setup Docker
        uses: docker-practice/actions-setup-docker@1.0.11

      - name: Init Docker
        run: |
          docker pull mysql:5.7
          docker pull redis
          docker-compose up -d

      - name: Build
        run: |
          go mod download
          go build -o ./output/webdict_server ./src/main/main.go
          cp ./run.sh ./output
          cp ./app.properties ./output

      - name: Test
        run: |
          ./output/webdict_server -PROD_TEST
